import type { CompetitionConfig } from "./types.ts";
import type {
  ChallengeTier,
  ChallengeTierId,
  SpecialistChallenge,
  SpecialistType,
} from "./types.ts";

export const competitionConfig: CompetitionConfig = {
  seasonId: "season-7",
  cohortDurationHours: 72,
  participantCap: 128,
  entryFeeUsd: 25,
  scoringWeights: {
    pnlPercent: 8.5,
    volumeUsd: 6,
    consistency: 0.28,
    winRate: 0.08,
    drawdownPenalty: 0.65,
  },
  prizePoolSplit: [0.48, 0.24, 0.14, 0.08, 0.06],
  fundedRewardShareBps: 450,
  minTrades: 5,
  minActiveDays: 2,
  presets: [
    {
      id: "macro-sprint",
      name: "Macro Sprint",
      focus: "RWA majors",
      tagline:
        "Trade the fastest-moving FX and macro pairs over a compressed window.",
      questRewardPoints: 70,
      streakMultiplier: 1.2,
      raffleTickets: 4,
    },
    {
      id: "carry-breaker",
      name: "Carry Breaker",
      focus: "Rates and commodities",
      tagline:
        "Reward disciplined rotation across oil, gold, and rate-sensitive narratives.",
      questRewardPoints: 90,
      streakMultiplier: 1.35,
      raffleTickets: 5,
    },
    {
      id: "crypto-impulse",
      name: "Crypto Impulse",
      focus: "Majors and beta",
      tagline: "High-energy cohort for volatile crypto perp specialists.",
      questRewardPoints: 60,
      streakMultiplier: 1.15,
      raffleTickets: 3,
    },
  ],
};

export const challengeTiers: Record<ChallengeTierId, ChallengeTier> = {
  sprint: {
    id: "sprint",
    name: "Sprint",
    entryFee: 1,
    profitTarget: 5,
    maxDrawdown: 4,
    dailyLossLimit: 3,
    durationDays: 2, // 48-hour micro-competition
    fundedEligible: false,
    retryDiscount: 30,
    minCapital: 25,
  },
  scout: {
    id: "scout",
    name: "Scout",
    entryFee: 2,
    profitTarget: 8,
    maxDrawdown: 5,
    dailyLossLimit: 3,
    durationDays: 7,
    fundedEligible: false,
    retryDiscount: 30,
    minCapital: 50,
  },
  ranger: {
    id: "ranger",
    name: "Ranger",
    entryFee: 5,
    profitTarget: 10,
    maxDrawdown: 8,
    dailyLossLimit: 4,
    durationDays: 10,
    fundedEligible: false,
    retryDiscount: 30,
    minCapital: 200,
  },
  veteran: {
    id: "veteran",
    name: "Veteran",
    entryFee: 10,
    profitTarget: 12,
    maxDrawdown: 6,
    dailyLossLimit: 3,
    durationDays: 10,
    fundedEligible: false,
    retryDiscount: 30,
    minCapital: 500,
  },
  elite: {
    id: "elite",
    name: "Elite",
    entryFee: 25,
    profitTarget: 15,
    maxDrawdown: 5,
    dailyLossLimit: 2.5,
    durationDays: 14,
    fundedEligible: true,
    retryDiscount: 30,
    minCapital: 2000,
  },
  apex: {
    id: "apex",
    name: "Apex",
    entryFee: 50,
    profitTarget: 15,
    maxDrawdown: 4,
    dailyLossLimit: 2,
    durationDays: 14,
    fundedEligible: true,
    retryDiscount: 30,
    minCapital: 5000,
  },
};

export const specialistChallenges: Record<SpecialistType, SpecialistChallenge> =
  {
    crypto: {
      type: "crypto",
      name: "Crypto Track",
      markets: ["BTC", "SOL", "BONK", "ETH"],
      bonusMultiplier: 1.1,
      launchPhase: 1,
    },
    metals: {
      type: "metals",
      name: "Metals Track",
      markets: ["XAU", "XAG"],
      bonusMultiplier: 1.2,
      launchPhase: 1,
    },
    energy: {
      type: "energy",
      name: "Energy Track",
      markets: ["WTI", "Brent", "NatGas"],
      bonusMultiplier: 1.2,
      launchPhase: 1,
    },
    forex: {
      type: "forex",
      name: "Forex Track",
      markets: ["EUR/USD", "GBP/USD", "USD/JPY"],
      bonusMultiplier: 1.15,
      launchPhase: 2,
    },
    multi_asset: {
      type: "multi_asset",
      name: "Multi-Asset Track",
      markets: ["BTC", "ETH", "XAU", "EUR/USD", "WTI"],
      bonusMultiplier: 1.25,
      launchPhase: 3,
    },
  };
